base:
  project: APS-fault-detection
  
data_source:
  raw_data_path: ./aps_failure_training_set1.csv
  MongoDB_database_name: sensors-streaming-data
  MongoDB_collection_name: APS_sensors_burrah

data_ingestion:
    feature_store_path: ./artifacts/data_ingestion/feature_store/sensors.csv
    test_size: 0.2
    training_data_path: ./artifacts/data_ingestion/training_data/training_set.csv
    test_data_path: ./artifacts/data_ingestion/test_data/test_set.csv
    random_state: 42

